### ISSUE TITLE
Add load balancing

### ISSUE THREAD

**Issue by MadisonBarks** [brendanashworth/Raw-TCP-Proxy#2]
Issue only here for me to mark my position, and to prevent another issue like this from coming up.

This is currently being worked on.

**Comment by brendanashworth** [comment]
Any update so far?

**Comment by MadisonBarks** [comment]
I've been busy with work and other projects.
I'll get around to it.
Biggest problem right now is detection of dead machines.

**Comment by brendanashworth** [comment]
Alright, no rush. If you want to send in some commits as you go along I can try and help out. I'd only merge it once you say its done.

**Comment by MadisonBarks** [comment]
Aight,  I'll send in what I have tonight. Although,  I'll admit, it's a
mess.

**Comment by brendanashworth** [comment]
push? @captgreen1

**Comment by MadisonBarks** [comment]
So fokin busy ;-;

**Comment by MadisonBarks** [comment]
Closing this for right now.
My branch still contains changes leading to the load balancing; however, as I don't have the time to work on this right now, that branch will become somewhat stale (and honestly, it's 18 commits behind this branch).

**Comment by brendanashworth** [comment]
Okay, got it.
